lib/evercam_wechat_web/router.ex
defmodule EvercamWechatWeb.Router do
  use EvercamWechatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Guardian.Plug.Pipeline,
      module: EvercamWechatWeb.Guardian,
      error_handler: EvercamWechatWeb.AuthErrorHandler

    plug Guardian.Plug.VerifySession, claims: %{"typ" => "access"}
    plug Guardian.Plug.VerifyHeader, claims: %{"typ" => "access"}
  end

  pipeline :ensure_auth do
    plug :auth
    plug Guardian.Plug.EnsureAuthenticated
    plug Guardian.Plug.LoadResource
  end

  pipeline :maybe_auth do
    plug :auth
    plug Guardian.Plug.LoadResource, allow_blank: true
  end

  scope "/", EvercamWechatWeb do
    pipe_through [:browser, :ensure_auth, :put_current_user]

    delete "/session", SessionController, :delete
    get "/live_snapshot", LiveSnapshotController, :index

    resources "/subscriptions", SubscriptionController,
      only: [:new, :create, :edit, :update],
      singleton: true

    resources "/snapshot_times", SnapshotTimeController, only: [:index, :show]
    resources "/users", UserController, only: [:edit, :update], singleton: true
  end

  scope "/", EvercamWechatWeb do
    pipe_through [:browser, :maybe_auth, :put_current_user]

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
  end

  scope "/auth", EvercamWechatWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/wechat", EvercamWechatWeb do
    resources "/", WechatController, only: [:index, :create]
  end

  defp put_current_user(conn, _opts) do
    current_user = EvercamWechatWeb.Guardian.Plug.current_resource(conn)
    assign(conn, :current_user, current_user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
end

lib/evercam_wechat_web/views/layout_view.ex
defmodule EvercamWechatWeb.LayoutView do
  use EvercamWechatWeb, :view
end

lib/evercam_wechat_web/templates/layout/_nav.html.eex
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link to: Routes.page_path(@conn, :index), class: "navbar-item" do %>
        <%= img_tag "/images/everlogo-1.png" %>
      <% end %>

      <%= link "Live", to: Routes.live_snapshot_path(@conn, :index), class: "navbar-item" %>
      <%= link "Updates", to: Routes.snapshot_time_path(@conn, :index), class: "navbar-item" %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-end">
        <%= if @conn.assigns[:current_user] do %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= @conn.assigns[:current_user].nickname %>
            </a>
            <div class="navbar-dropdown">
              <%= link "Edit account", to: Routes.user_path(@conn, :edit), class: "navbar-item" %>
              <%= link "Edit updates preference", to: Routes.subscription_path(@conn, :edit), class: "navbar-item" %>

              <hr class="navbar-divider">
              <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete, class: "navbar-item" %>
            </div>
          </div>
        <% else %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link "Sign in", to: Routes.auth_path(@conn, :request, :wechat), class: "button is-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

lib/evercam_wechat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"/>
    <title>Evercam</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "_nav.html", conn: @conn %>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>